### ISSUE TITLE
suggest: a option for only extend single method

### ISSUE THREAD

**Issue by Cologler** [borzunov/dontasq#1]
currently:

``` py
[].where(...)
```

expected:

``` py
[].query().where(...) # `.query()` return a `Queryable(self)`
```

**Comment by borzunov** [comment]
Hi @Cologler,

I don't know how to implement such an option without breaking the current interface.

**Comment by Cologler** [comment]
Maybe just add a method without remove exists methods?

Or use some configuration like `os.environ`?

**Comment by borzunov** [comment]
Adding `.query()` without removing existing methods looks good to me.

Unfortunately, I don't have time to implement this right now. Would you consider making a pull request?

If you do, please also add tests for this method.
